version: '3.9'

services:
    api:
        container_name: 'job-finder-api'
        build:
            context: .
            dockerfile: Dockerfile.prod
        environment:
            - APPVERSION=${APPVERSION}
            - ENV=${ENV}
            - SESSION_SECRET=${SESSION_SECRET}
            - PORT=${PORT}
            - DBNAME=${DBNAME}
            - DBUSER=${DBUSER}
            - DBPASS=${DBPASS}
            - DBHOST=${DBHOST}
            - DBPORT=${DBPORT}
            - DBSSL=${DBSSL}
            - DBSSL_REJECT_UNAUTHORIZED=${DBSSL_REJECT_UNAUTHORIZED}
            - DBSYNC=${DBSYNC}
            - URL_CLIENT=${URL_CLIENT}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_AUTH_USER=${EMAIL_AUTH_USER}
            - EMAIL_AUTH_PASS=${EMAIL_AUTH_PASS}
            - EMAIL_SECURE=${EMAIL_SECURE}
            - EMAIL_REQUIRE_TLS=${EMAIL_REQUIRE_TLS}
            - EMAIL_DISABLE_URL_ACCESS=${EMAIL_DISABLE_URL_ACCESS}
            - EMAIL_REJECT_UNAUTHORIZED=${EMAIL_REJECT_UNAUTHORIZED}
            - CLOUDINARY_URL=${CLOUDINARY_URL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_SECRET_ID=${GOOGLE_SECRET_ID}
        ports:
            - '4000:4000'
